### PR TITLE
Add default rpc port

### PR DESCRIPTION
**Pull request by ts468**

### CODE REVIEW

**Comment by taoeffect** [comment]
Since this was a very minor change we'll wait until more stuff is added before releasing another point update.

**Comment by ts468** [comment]
Thanks for the fast merge! I'm about to integrate dnschain into NixOS and I hoped I could use the updated version for it. However, that would require it to be available as NPM package. Can you estimate how long it will take until the next release?

**Comment by taoeffect** [comment]
You should be able to set up everything you need without this change.

You've got a lot of options:

- Create the `namecoin.conf` file that DNSChain reads (you can even tell DNSChain where to look for it if you don't like the default location for some reason), and set your `rpcport` value there.
- You might even be able to just set it via an environment variable for a command line option since we use `nconf` (look at nconf's docs for more info on how to do that, I don't remember, but it might be as simple as setting `RPCPORT=8336`).

**Comment by ts468** [comment]
Thanks! Unfortunately, I can't use namecoin.conf the way other Linux distributions do. I can have a look whether I can set it as an environment variable, but somehow the cleanest solution would definitely be a new release ;)

**Comment by ts468** [comment]
But don't worry, I can patch things locally as well!

**Comment by taoeffect** [comment]
Oh, and the environment variable (or cli args) probably should be capitalized exactly as it is in the conf, so `rpcport=8336` (and keep in mind that if you use any other blockchain with that same named conf variable, it will set it to that as well, which would result in a conflict).

**Pull request merged**
